// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCommunityMember(ctx context.Context, arg AddCommunityMemberParams) (CommunityMember, error)
	AddEventParticipant(ctx context.Context, arg AddEventParticipantParams) (EventParticipant, error)
	AdminConfirmMatch(ctx context.Context, arg AdminConfirmMatchParams) (Match, error)
	CheckFriendship(ctx context.Context, arg CheckFriendshipParams) (bool, error)
	ConfirmMatch(ctx context.Context, arg ConfirmMatchParams) (Match, error)
	CountCommunities(ctx context.Context, arg CountCommunitiesParams) (int64, error)
	CountCommunityMembers(ctx context.Context, arg CountCommunityMembersParams) (int64, error)
	CountEvents(ctx context.Context, arg CountEventsParams) (int64, error)
	CountGlobalLeaderboard(ctx context.Context, minGames pgtype.Int4) (int64, error)
	CountMutualCommunities(ctx context.Context, arg CountMutualCommunitiesParams) (int64, error)
	CountMyMatches(ctx context.Context, arg CountMyMatchesParams) (int64, error)
	CountNotifications(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error)
	CreateCommunity(ctx context.Context, arg CreateCommunityParams) (Community, error)
	CreateCommunityChat(ctx context.Context, arg CreateCommunityChatParams) (CreateCommunityChatRow, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateEventChat(ctx context.Context, arg CreateEventChatParams) (CreateEventChatRow, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// Notifications queries
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePersonalChat(ctx context.Context, arg CreatePersonalChatParams) (CreatePersonalChatRow, error)
	CreateUser(ctx context.Context, phone string) (User, error)
	DeleteCommunityMember(ctx context.Context, arg DeleteCommunityMemberParams) error
	DeleteEvent(ctx context.Context, id pgtype.UUID) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DisputeMatch(ctx context.Context, arg DisputeMatchParams) (Match, error)
	GetCalendarEvents(ctx context.Context, arg GetCalendarEventsParams) ([]GetCalendarEventsRow, error)
	GetChatByID(ctx context.Context, id pgtype.UUID) (GetChatByIDRow, error)
	GetChatMembersForCommunity(ctx context.Context, chatID pgtype.UUID) ([]pgtype.UUID, error)
	GetChatMembersForEvent(ctx context.Context, chatID pgtype.UUID) ([]pgtype.UUID, error)
	GetChatMembersForPersonal(ctx context.Context, id pgtype.UUID) ([]GetChatMembersForPersonalRow, error)
	GetCommunityBasicInfo(ctx context.Context, id pgtype.UUID) (GetCommunityBasicInfoRow, error)
	GetCommunityByID(ctx context.Context, id pgtype.UUID) (Community, error)
	GetCommunityBySlug(ctx context.Context, slug pgtype.Text) (Community, error)
	GetCommunityChatByCommunityID(ctx context.Context, communityID pgtype.UUID) (GetCommunityChatByCommunityIDRow, error)
	GetCommunityLeaderboard(ctx context.Context, arg GetCommunityLeaderboardParams) ([]GetCommunityLeaderboardRow, error)
	GetCommunityMember(ctx context.Context, arg GetCommunityMemberParams) (CommunityMember, error)
	GetEventBasicInfo(ctx context.Context, id pgtype.UUID) (GetEventBasicInfoRow, error)
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	GetEventChatByEventID(ctx context.Context, eventID pgtype.UUID) (GetEventChatByEventIDRow, error)
	GetEventParticipant(ctx context.Context, arg GetEventParticipantParams) (EventParticipant, error)
	GetGlobalLeaderboard(ctx context.Context, arg GetGlobalLeaderboardParams) ([]GetGlobalLeaderboardRow, error)
	GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error)
	GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error)
	GetMessages(ctx context.Context, arg GetMessagesParams) ([]GetMessagesRow, error)
	GetPersonalChat(ctx context.Context, arg GetPersonalChatParams) (GetPersonalChatRow, error)
	GetPlayerTotalGames(ctx context.Context, userID pgtype.UUID) (int32, error)
	GetRatingHistory(ctx context.Context, arg GetRatingHistoryParams) ([]RatingHistory, error)
	GetTotalUnreadCount(ctx context.Context, userID pgtype.UUID) (int32, error)
	GetUnreadNotificationCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetUserBadges(ctx context.Context, userID pgtype.UUID) ([]GetUserBadgesRow, error)
	GetUserBasicInfo(ctx context.Context, id pgtype.UUID) (GetUserBasicInfoRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserCommunities(ctx context.Context, userID pgtype.UUID) ([]GetUserCommunitiesRow, error)
	GetUserCommunityRatings(ctx context.Context, userID pgtype.UUID) ([]GetUserCommunityRatingsRow, error)
	GetUserForRating(ctx context.Context, id pgtype.UUID) (GetUserForRatingRow, error)
	GetUserRatingPosition(ctx context.Context, userID pgtype.UUID) (GetUserRatingPositionRow, error)
	GetUserStats(ctx context.Context, userID pgtype.UUID) (PlayerStatsGlobal, error)
	InsertRatingHistory(ctx context.Context, arg InsertRatingHistoryParams) (RatingHistory, error)
	IsUserInChat(ctx context.Context, arg IsUserInChatParams) (bool, error)
	ListCommunities(ctx context.Context, arg ListCommunitiesParams) ([]ListCommunitiesRow, error)
	ListCommunityMembers(ctx context.Context, arg ListCommunityMembersParams) ([]ListCommunityMembersRow, error)
	ListEventParticipants(ctx context.Context, eventID pgtype.UUID) ([]ListEventParticipantsRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error)
	ListMyChats(ctx context.Context, userID pgtype.UUID) ([]ListMyChatsRow, error)
	ListMyCommunities(ctx context.Context, userID pgtype.UUID) ([]ListMyCommunitiesRow, error)
	ListMyCreatedEvents(ctx context.Context, arg ListMyCreatedEventsParams) ([]ListMyCreatedEventsRow, error)
	ListMyJoinedEvents(ctx context.Context, arg ListMyJoinedEventsParams) ([]ListMyJoinedEventsRow, error)
	ListMyMatches(ctx context.Context, arg ListMyMatchesParams) ([]Match, error)
	ListMyPastEvents(ctx context.Context, arg ListMyPastEventsParams) ([]ListMyPastEventsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	RemoveEventParticipant(ctx context.Context, arg RemoveEventParticipantParams) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	SubmitMatchResult(ctx context.Context, arg SubmitMatchResultParams) (Match, error)
	UpdateChatLastMessage(ctx context.Context, arg UpdateChatLastMessageParams) error
	UpdateChatMuted(ctx context.Context, arg UpdateChatMutedParams) error
	UpdateCommunity(ctx context.Context, arg UpdateCommunityParams) (Community, error)
	UpdateCommunityMemberRole(ctx context.Context, arg UpdateCommunityMemberRoleParams) (CommunityMember, error)
	UpdateCommunityMemberStats(ctx context.Context, arg UpdateCommunityMemberStatsParams) error
	UpdateCommunityMemberStatus(ctx context.Context, arg UpdateCommunityMemberStatusParams) (CommunityMember, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error)
	UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (UpdateEventStatusRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) (UpdateUserAvatarURLRow, error)
	UpdateUserNTRPLevel(ctx context.Context, arg UpdateUserNTRPLevelParams) error
	UpdateUserRating(ctx context.Context, arg UpdateUserRatingParams) error
	UpsertChatReadStatus(ctx context.Context, arg UpsertChatReadStatusParams) error
	UpsertPlayerStatsGlobal(ctx context.Context, arg UpsertPlayerStatsGlobalParams) error
}

var _ Querier = (*Queries)(nil)
