// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCommunityMember(ctx context.Context, arg AddCommunityMemberParams) (CommunityMember, error)
	AddEventParticipant(ctx context.Context, arg AddEventParticipantParams) (EventParticipant, error)
	CheckFriendship(ctx context.Context, arg CheckFriendshipParams) (bool, error)
	CountCommunities(ctx context.Context, arg CountCommunitiesParams) (int64, error)
	CountCommunityMembers(ctx context.Context, arg CountCommunityMembersParams) (int64, error)
	CountEvents(ctx context.Context, arg CountEventsParams) (int64, error)
	CountMutualCommunities(ctx context.Context, arg CountMutualCommunitiesParams) (int64, error)
	CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error)
	CreateCommunity(ctx context.Context, arg CreateCommunityParams) (Community, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, phone string) (User, error)
	DeleteCommunityMember(ctx context.Context, arg DeleteCommunityMemberParams) error
	DeleteEvent(ctx context.Context, id pgtype.UUID) error
	GetCalendarEvents(ctx context.Context, arg GetCalendarEventsParams) ([]GetCalendarEventsRow, error)
	GetCommunityByID(ctx context.Context, id pgtype.UUID) (Community, error)
	GetCommunityBySlug(ctx context.Context, slug pgtype.Text) (Community, error)
	GetCommunityLeaderboard(ctx context.Context, arg GetCommunityLeaderboardParams) ([]GetCommunityLeaderboardRow, error)
	GetCommunityMember(ctx context.Context, arg GetCommunityMemberParams) (CommunityMember, error)
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	GetEventParticipant(ctx context.Context, arg GetEventParticipantParams) (EventParticipant, error)
	GetUserBadges(ctx context.Context, userID pgtype.UUID) ([]GetUserBadgesRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserCommunities(ctx context.Context, userID pgtype.UUID) ([]GetUserCommunitiesRow, error)
	GetUserStats(ctx context.Context, userID pgtype.UUID) (PlayerStatsGlobal, error)
	ListCommunities(ctx context.Context, arg ListCommunitiesParams) ([]ListCommunitiesRow, error)
	ListCommunityMembers(ctx context.Context, arg ListCommunityMembersParams) ([]ListCommunityMembersRow, error)
	ListEventParticipants(ctx context.Context, eventID pgtype.UUID) ([]ListEventParticipantsRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error)
	ListMyCommunities(ctx context.Context, userID pgtype.UUID) ([]ListMyCommunitiesRow, error)
	ListMyCreatedEvents(ctx context.Context, arg ListMyCreatedEventsParams) ([]ListMyCreatedEventsRow, error)
	ListMyJoinedEvents(ctx context.Context, arg ListMyJoinedEventsParams) ([]ListMyJoinedEventsRow, error)
	ListMyPastEvents(ctx context.Context, arg ListMyPastEventsParams) ([]ListMyPastEventsRow, error)
	RemoveEventParticipant(ctx context.Context, arg RemoveEventParticipantParams) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	UpdateCommunity(ctx context.Context, arg UpdateCommunityParams) (Community, error)
	UpdateCommunityMemberRole(ctx context.Context, arg UpdateCommunityMemberRoleParams) (CommunityMember, error)
	UpdateCommunityMemberStatus(ctx context.Context, arg UpdateCommunityMemberStatusParams) (CommunityMember, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error)
	UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (UpdateEventStatusRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) (UpdateUserAvatarURLRow, error)
}

var _ Querier = (*Queries)(nil)
