// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*)
FROM users
WHERE status = 'active'
  AND is_profile_complete = TRUE
  AND ($1::decimal IS NULL OR ntrp_level >= $1)
  AND ($2::decimal IS NULL OR ntrp_level <= $2)
  AND ($3::text IS NULL OR district = $3)
  AND ($4::gender_type IS NULL OR gender = $4)
  AND ($5::text IS NULL OR (first_name || ' ' || last_name) ILIKE '%' || $5 || '%')
`

type CountSearchUsersParams struct {
	MinLevel pgtype.Numeric `json:"min_level"`
	MaxLevel pgtype.Numeric `json:"max_level"`
	District pgtype.Text    `json:"district"`
	Gender   NullGenderType `json:"gender"`
	Query    pgtype.Text    `json:"query"`
}

func (q *Queries) CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers,
		arg.MinLevel,
		arg.MaxLevel,
		arg.District,
		arg.Gender,
		arg.Query,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    phone
) VALUES (
    $1
)
RETURNING id, phone, phone_verified,
    first_name, last_name, gender, birth_year, city, district, avatar_url, bio,
    ntrp_level, level_label, quiz_completed,
    global_rating, global_games_count,
    language, pin_hash, push_token, platform_role,
    profile_visibility, allow_messages_from, show_stats,
    notification_settings,
    status, is_profile_complete, last_active_at,
    created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PhoneVerified,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthYear,
		&i.City,
		&i.District,
		&i.AvatarUrl,
		&i.Bio,
		&i.NtrpLevel,
		&i.LevelLabel,
		&i.QuizCompleted,
		&i.GlobalRating,
		&i.GlobalGamesCount,
		&i.Language,
		&i.PinHash,
		&i.PushToken,
		&i.PlatformRole,
		&i.ProfileVisibility,
		&i.AllowMessagesFrom,
		&i.ShowStats,
		&i.NotificationSettings,
		&i.Status,
		&i.IsProfileComplete,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, phone_verified,
    first_name, last_name, gender, birth_year, city, district, avatar_url, bio,
    ntrp_level, level_label, quiz_completed,
    global_rating, global_games_count,
    language, pin_hash, push_token, platform_role,
    profile_visibility, allow_messages_from, show_stats,
    notification_settings,
    status, is_profile_complete, last_active_at,
    created_at, updated_at
FROM users
WHERE id = $1 AND status != 'deleted'
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PhoneVerified,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthYear,
		&i.City,
		&i.District,
		&i.AvatarUrl,
		&i.Bio,
		&i.NtrpLevel,
		&i.LevelLabel,
		&i.QuizCompleted,
		&i.GlobalRating,
		&i.GlobalGamesCount,
		&i.Language,
		&i.PinHash,
		&i.PushToken,
		&i.PlatformRole,
		&i.ProfileVisibility,
		&i.AllowMessagesFrom,
		&i.ShowStats,
		&i.NotificationSettings,
		&i.Status,
		&i.IsProfileComplete,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, phone_verified,
    first_name, last_name, gender, birth_year, city, district, avatar_url, bio,
    ntrp_level, level_label, quiz_completed,
    global_rating, global_games_count,
    language, pin_hash, push_token, platform_role,
    profile_visibility, allow_messages_from, show_stats,
    notification_settings,
    status, is_profile_complete, last_active_at,
    created_at, updated_at
FROM users
WHERE phone = $1 AND status != 'deleted'
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PhoneVerified,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthYear,
		&i.City,
		&i.District,
		&i.AvatarUrl,
		&i.Bio,
		&i.NtrpLevel,
		&i.LevelLabel,
		&i.QuizCompleted,
		&i.GlobalRating,
		&i.GlobalGamesCount,
		&i.Language,
		&i.PinHash,
		&i.PushToken,
		&i.PlatformRole,
		&i.ProfileVisibility,
		&i.AllowMessagesFrom,
		&i.ShowStats,
		&i.NotificationSettings,
		&i.Status,
		&i.IsProfileComplete,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, phone, phone_verified,
    first_name, last_name, gender, birth_year, city, district, avatar_url, bio,
    ntrp_level, level_label, quiz_completed,
    global_rating, global_games_count,
    language, platform_role,
    profile_visibility, show_stats,
    status, is_profile_complete, last_active_at,
    created_at, updated_at
FROM users
WHERE status = 'active'
  AND is_profile_complete = TRUE
  AND ($1::decimal IS NULL OR ntrp_level >= $1)
  AND ($2::decimal IS NULL OR ntrp_level <= $2)
  AND ($3::text IS NULL OR district = $3)
  AND ($4::gender_type IS NULL OR gender = $4)
  AND ($5::text IS NULL OR (first_name || ' ' || last_name) ILIKE '%' || $5 || '%')
ORDER BY
    CASE WHEN $6::text = 'rating' THEN global_rating END DESC,
    CASE WHEN $6::text = 'name' THEN first_name END ASC,
    CASE WHEN $6::text = 'games' THEN global_games_count END DESC,
    CASE WHEN $6::text = 'activity' THEN last_active_at END DESC NULLS LAST,
    global_rating DESC
LIMIT $8 OFFSET $7
`

type SearchUsersParams struct {
	MinLevel     pgtype.Numeric `json:"min_level"`
	MaxLevel     pgtype.Numeric `json:"max_level"`
	District     pgtype.Text    `json:"district"`
	Gender       NullGenderType `json:"gender"`
	Query        pgtype.Text    `json:"query"`
	SortBy       string         `json:"sort_by"`
	ResultOffset int32          `json:"result_offset"`
	ResultLimit  int32          `json:"result_limit"`
}

type SearchUsersRow struct {
	ID                pgtype.UUID        `json:"id"`
	Phone             string             `json:"phone"`
	PhoneVerified     pgtype.Bool        `json:"phone_verified"`
	FirstName         pgtype.Text        `json:"first_name"`
	LastName          pgtype.Text        `json:"last_name"`
	Gender            NullGenderType     `json:"gender"`
	BirthYear         pgtype.Int2        `json:"birth_year"`
	City              pgtype.Text        `json:"city"`
	District          pgtype.Text        `json:"district"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Bio               pgtype.Text        `json:"bio"`
	NtrpLevel         pgtype.Numeric     `json:"ntrp_level"`
	LevelLabel        pgtype.Text        `json:"level_label"`
	QuizCompleted     pgtype.Bool        `json:"quiz_completed"`
	GlobalRating      pgtype.Numeric     `json:"global_rating"`
	GlobalGamesCount  pgtype.Int4        `json:"global_games_count"`
	Language          pgtype.Text        `json:"language"`
	PlatformRole      NullPlatformRole   `json:"platform_role"`
	ProfileVisibility pgtype.Text        `json:"profile_visibility"`
	ShowStats         pgtype.Bool        `json:"show_stats"`
	Status            NullUserStatus     `json:"status"`
	IsProfileComplete pgtype.Bool        `json:"is_profile_complete"`
	LastActiveAt      pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.MinLevel,
		arg.MaxLevel,
		arg.District,
		arg.Gender,
		arg.Query,
		arg.SortBy,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.PhoneVerified,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.BirthYear,
			&i.City,
			&i.District,
			&i.AvatarUrl,
			&i.Bio,
			&i.NtrpLevel,
			&i.LevelLabel,
			&i.QuizCompleted,
			&i.GlobalRating,
			&i.GlobalGamesCount,
			&i.Language,
			&i.PlatformRole,
			&i.ProfileVisibility,
			&i.ShowStats,
			&i.Status,
			&i.IsProfileComplete,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    first_name           = COALESCE($1, first_name),
    last_name            = COALESCE($2, last_name),
    gender               = COALESCE($3, gender),
    birth_year           = COALESCE($4, birth_year),
    city                 = COALESCE($5, city),
    district             = COALESCE($6, district),
    avatar_url           = COALESCE($7, avatar_url),
    bio                  = COALESCE($8, bio),
    ntrp_level           = COALESCE($9, ntrp_level),
    level_label          = COALESCE($10, level_label),
    quiz_completed       = COALESCE($11, quiz_completed),
    global_rating        = COALESCE($12, global_rating),
    global_games_count   = COALESCE($13, global_games_count),
    language             = COALESCE($14, language),
    pin_hash             = COALESCE($15, pin_hash),
    push_token           = COALESCE($16, push_token),
    profile_visibility   = COALESCE($17, profile_visibility),
    allow_messages_from  = COALESCE($18, allow_messages_from),
    show_stats           = COALESCE($19, show_stats),
    notification_settings = COALESCE($20, notification_settings),
    is_profile_complete  = COALESCE($21, is_profile_complete),
    last_active_at       = COALESCE($22, last_active_at),
    updated_at           = NOW()
WHERE id = $23 AND status != 'deleted'
RETURNING id, phone, phone_verified,
    first_name, last_name, gender, birth_year, city, district, avatar_url, bio,
    ntrp_level, level_label, quiz_completed,
    global_rating, global_games_count,
    language, pin_hash, push_token, platform_role,
    profile_visibility, allow_messages_from, show_stats,
    notification_settings,
    status, is_profile_complete, last_active_at,
    created_at, updated_at
`

type UpdateUserParams struct {
	FirstName            pgtype.Text        `json:"first_name"`
	LastName             pgtype.Text        `json:"last_name"`
	Gender               NullGenderType     `json:"gender"`
	BirthYear            pgtype.Int2        `json:"birth_year"`
	City                 pgtype.Text        `json:"city"`
	District             pgtype.Text        `json:"district"`
	AvatarUrl            pgtype.Text        `json:"avatar_url"`
	Bio                  pgtype.Text        `json:"bio"`
	NtrpLevel            pgtype.Numeric     `json:"ntrp_level"`
	LevelLabel           pgtype.Text        `json:"level_label"`
	QuizCompleted        pgtype.Bool        `json:"quiz_completed"`
	GlobalRating         pgtype.Numeric     `json:"global_rating"`
	GlobalGamesCount     pgtype.Int4        `json:"global_games_count"`
	Language             pgtype.Text        `json:"language"`
	PinHash              pgtype.Text        `json:"pin_hash"`
	PushToken            pgtype.Text        `json:"push_token"`
	ProfileVisibility    pgtype.Text        `json:"profile_visibility"`
	AllowMessagesFrom    pgtype.Text        `json:"allow_messages_from"`
	ShowStats            pgtype.Bool        `json:"show_stats"`
	NotificationSettings []byte             `json:"notification_settings"`
	IsProfileComplete    pgtype.Bool        `json:"is_profile_complete"`
	LastActiveAt         pgtype.Timestamptz `json:"last_active_at"`
	ID                   pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.BirthYear,
		arg.City,
		arg.District,
		arg.AvatarUrl,
		arg.Bio,
		arg.NtrpLevel,
		arg.LevelLabel,
		arg.QuizCompleted,
		arg.GlobalRating,
		arg.GlobalGamesCount,
		arg.Language,
		arg.PinHash,
		arg.PushToken,
		arg.ProfileVisibility,
		arg.AllowMessagesFrom,
		arg.ShowStats,
		arg.NotificationSettings,
		arg.IsProfileComplete,
		arg.LastActiveAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PhoneVerified,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthYear,
		&i.City,
		&i.District,
		&i.AvatarUrl,
		&i.Bio,
		&i.NtrpLevel,
		&i.LevelLabel,
		&i.QuizCompleted,
		&i.GlobalRating,
		&i.GlobalGamesCount,
		&i.Language,
		&i.PinHash,
		&i.PushToken,
		&i.PlatformRole,
		&i.ProfileVisibility,
		&i.AllowMessagesFrom,
		&i.ShowStats,
		&i.NotificationSettings,
		&i.Status,
		&i.IsProfileComplete,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
